### ISSUE TITLE
Link error building on macOS 10.13.6

### ISSUE THREAD

**Issue by tinunkai** [farseerfc/ydcv-rs#16]
Have some problems when linking.
```
error: linking with `cc` failed: exit code: 1
.
.
.
  = note: ld: library not found for -lxcb
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Using cargo 1.28.0, rustc 1.28.0, cc 9.1.0(clang-902.0.39.2).
I googled lxcb but didn't find some useful information.
Am I missing some dependencies?

Thank you.

**Comment by farseerfc** [comment]
`xcb` is the C binding for X11 protocol, which should be provided by XQuartz on macOS. We use x11-clipboard for reading X11 selection (not just clipboard contents). I can try make this an optional feature.

**Comment by tinunkai** [comment]
谢谢！

**Comment by farseerfc** [comment]
Just made `x11-clipboard` feature optional for ydcv-rs 0.3.9 .
Please test on macOS with `cargo build --no-default-features`
