### ISSUE TITLE
Use the same environment variable as ydcv

### ISSUE THREAD

**Issue by pickfire** [farseerfc/ydcv-rs#21]
https://github.com/farseerfc/ydcv-rs/blob/master/src/ydclient.rs#L14

maybe we could use the same as ydcv environment variable names (`YDCV_YOUDAO_APPID`) to keep consistency?

https://github.com/felixonmars/ydcv/blob/0.7/src/ydcv.py#L32

**Comment by farseerfc** [comment]
Thank you for the suggestion! Have implemented the same envvar in 0.4.5
