### ISSUE TITLE
非Qt程序上的无延迟翻译 & 误翻译fcitx输入

### ISSUE THREAD

**Issue by Reverier-Xu** [farseerfc/ydcv-rs#27]
系统环境: `Arch Linux KDE`

Bug情况: 使用`ydcv -x -n`开启屏幕取词, 在非Qt应用程序中(例如Chrome和PyCharm), 使用fcitx输入时会自动翻译fcitx的第一选项, 在选择非Qt应用程序上的文字时, 翻译几乎是无延迟的, 例如我选取了`comment`, 那么会弹出来一堆翻译窗口, 从`c`, `co`...翻译到`comment`. 但在Qt应用程序(例如Konsole)上屏幕取词是正常工作的, 使用fcitx也不会产生上述情况.

**Comment by tuberry** [comment]
这应该都是 Gtk+ 的锅。首先是剪切板一旦更改就发信号，这对鼠标划选的 primary selection 来说就比较难受了。另外输入法提交文本大概是一个选取预编辑文本（preedit-text）后替换的过程（你提交文本后按鼠标中键就能粘贴预编辑文本）。

**Comment by farseerfc** [comment]
這裏有兩個問題：

1. fcitx 的輸入預編輯框被當作 primary selection ：
我這邊 Arch Linux KDE 環境下無法復現該問題……不過可以猜想有兩個地方相關：
是否啓用了 GTK 的 IM module ？ `fcitx-diagnose` 命令可以查看 GTK IM module 的啓用狀況。
是否啓用了 preedit ？ 
使用了 GTK IM module 之後應該不會有這個現象了。

2. 選擇文本時逐字彈出。
這個是 primary selection 選擇範圍在選擇的過程中就更改了的情況。
代碼中爲了避免太過惱人，每次獲取 primary selection 有間隔 1s 的設置：
https://github.com/farseerfc/ydcv-rs/blob/master/src/main.rs#L193
或許未來版本中可以考慮通過選項更改這個值？

**Comment by farseerfc** [comment]
增加了 `-i/--interval` 選項，默認值保持以前的設置（windows 上 1s，unix 上 0）。
