### ISSUE TITLE
error: failed to run custom build command for `libdbus-sys v0.2.1`

### ISSUE THREAD

**Issue by gddg** [farseerfc/ydcv-rs#28]
ubuntu 18.4 
cargo build :
error: failed to run custom build command for `libdbus-sys v0.2.1`

need install : 
 
sudo apt install libdbus-glib-1-dev

**Comment by farseerfc** [comment]
Can you try `sudo apt install libdbus-glib-1-dev` ?

**Comment by farseerfc** [comment]
No reply for a month, closing this issue.

**Comment by smsourov** [comment]
Yes. Now it works. 

> Can you try `sudo apt install libdbus-glib-1-dev` ?
