### ISSUE TITLE
Rename crate from 'ydcv-rs' to 'ydcv'

### ISSUE THREAD

**Issue by dtolnay** [farseerfc/ydcv-rs#4]
Every crate on crates.io is for Rust :smile: no reason for the -rs suffix.

**Comment by farseerfc** [comment]
> Every crate on crates.io is for Rust 

True

> no reason for the -rs suffix

But what if this package is a rust re-implementation of some well-known tool in other language?
In this case `ydcv-rs` is a drop-in re-implementation of [ydcv](https://github.com/felixonmars/ydcv), and `ydcv-rs` have the potential to coexist with the original `ydcv` on other sites. I don't want to conflict with the original `ydcv` in all cases.

I found it is a common practice to [name a crate as *-rs](https://crates.io/search?q=-rs) for rust re-implementations and rust bindings of well-known packages in other languages.

**Comment by dtolnay** [comment]
Makes sense, thanks for the explanation.
